# Generated by Django 4.2.4 on 2023-09-04 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_comments_options_article_liked_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='Liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
